In [1]:
print("AI-Powered Packaging Chatbot")
print("PackPro Solutions")
print("Week 3 Project")

AI-Powered Packaging Chatbot
PackPro Solutions
Week 3 Project

In [2]:
company_name = "PackPro Solutions"
project_name = "AI-Powered Packaging Chatbot"

print("Company:", company_name)
print("Project:", project_name)

Company: PackPro Solutions
Project: AI-Powered Packaging Chatbot

In [3]:
!pip install scikit-learn pandas

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import json
import re
import os
from datetime import datetime

import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
knowledge_base = [
    {
        "category": "products",
        "question": "What products do you offer?",
        "answer": "PackPro Solutions offers custom boxes, mailer boxes, gift boxes, food packaging, kraft packaging, and e-commerce packaging."
    },
    {
        "category": "products",
        "question": "Do you make custom boxes?",
        "answer": "Yes. We manufacture customized packaging boxes according to your required size, material, printing and finishing."
    },
    {
        "category": "products",
        "question": "Do you make mailer boxes?",
        "answer": "Yes. We provide custom mailer boxes suitable for e-commerce and product shipping."
    },
    {
        "category": "products",
        "question": "Do you make gift boxes?",
        "answer": "Yes. We offer customized gift boxes with different materials, printing and finishing options."
    },
    {
        "category": "materials",
        "question": "What materials do you use?",
        "answer": "We offer kraft paper, corrugated cardboard, paperboard and rigid board packaging."
    },
    {
        "category": "materials",
        "question": "Do you offer kraft packaging?",
        "answer": "Yes. Kraft packaging is available for several custom packaging products."
    },
    {
        "category": "customization",
        "question": "Can I customize the box size?",
        "answer": "Yes. Customers can provide custom length, width and height requirements."
    },
    {
        "category": "customization",
        "question": "Can you print my logo?",
        "answer": "Yes. We provide custom logo and artwork printing on suitable packaging products."
    },
    {
        "category": "customization",
        "question": "What finishing options are available?",
        "answer": "Available finishing options may include matte or gloss finishing, foiling and embossing depending on the packaging type."
    },
    {
        "category": "moq",
        "question": "What is your MOQ?",
        "answer": "Our standard minimum order quantity is 100 units, although MOQ can vary depending on the product and customization."
    },
    {
        "category": "moq",
        "question": "What is the minimum order quantity?",
        "answer": "Our standard minimum order quantity is 100 units. Some customized products may have different requirements."
    },
    {
        "category": "samples",
        "question": "Can I get a sample?",
        "answer": "Yes. Samples can be requested before placing a bulk production order."
    },
    {
        "category": "production",
        "question": "How long does production take?",
        "answer": "Standard production generally takes 7 to 14 business days after artwork approval."
    },
    {
        "category": "production",
        "question": "How long will my order take?",
        "answer": "The standard production time is approximately 7 to 14 business days after artwork approval."
    },
    {
        "category": "delivery",
        "question": "Do you provide delivery?",
        "answer": "Yes. Delivery arrangements can be discussed based on the customer's location and order requirements."
    },
    {
        "category": "quotation",
        "question": "How can I get a quotation?",
        "answer": "To request a quotation, provide the product type, dimensions, quantity, material, printing requirements, finishing and delivery city."
    },
    {
        "category": "quotation",
        "question": "What information is needed for a quote?",
        "answer": "We need your product type, length, width, height, quantity, material, printing requirements, finishing and delivery city."
    },
    {
        "category": "pricing",
        "question": "What affects packaging price?",
        "answer": "Packaging price depends on product type, dimensions, quantity, material, printing, finishing and delivery requirements."
    },
    {
        "category": "company",
        "question": "What is PackPro Solutions?",
        "answer": "PackPro Solutions is an emerging packaging company providing customized packaging solutions for businesses, retailers and e-commerce brands."
    },
    {
        "category": "support",
        "question": "Can I speak to the sales team?",
        "answer": "Yes. If your question requires a customized quotation or information outside the knowledge base, please contact the PackPro Solutions sales team."
    }
]

print("Knowledge Base Created!")
print("Total records:", len(knowledge_base))

Knowledge Base Created!
Total records: 20

In [6]:
with open("packaging_knowledge.json", "w", encoding="utf-8") as file:
    json.dump(knowledge_base, file, indent=4)

print("packaging_knowledge.json created successfully!")

packaging_knowledge.json created successfully!

In [7]:
df = pd.DataFrame(knowledge_base)

display(df)

,category,question,answer
0,products,What products do you offer?,"PackPro Solutions offers custom boxes, mailer ..."
1,products,Do you make custom boxes?,Yes. We manufacture customized packaging boxes...
2,products,Do you make mailer boxes?,Yes. We provide custom mailer boxes suitable f...
3,products,Do you make gift boxes?,Yes. We offer customized gift boxes with diffe...
4,materials,What materials do you use?,"We offer kraft paper, corrugated cardboard, pa..."
5,materials,Do you offer kraft packaging?,Yes. Kraft packaging is available for several ...
6,customization,Can I customize the box size?,"Yes. Customers can provide custom length, widt..."
7,customization,Can you print my logo?,Yes. We provide custom logo and artwork printi...
8,customization,What finishing options are available?,Available finishing options may include matte ...
9,moq,What is your MOQ?,Our standard minimum order quantity is 100 uni...
10,moq,What is the minimum order quantity?,Our standard minimum order quantity is 100 uni...
11,samples,Can I get a sample?,Yes. Samples can be requested before placing a...
12,production,How long does production take?,Standard production generally takes 7 to 14 bu...
13,production,How long will my order take?,The standard production time is approximately ...
14,delivery,Do you provide delivery?,Yes. Delivery arrangements can be discussed ba...
15,quotation,How can I get a quotation?,"To request a quotation, provide the product ty..."
16,quotation,What information is needed for a quote?,"We need your product type, length, width, heig..."
17,pricing,What affects packaging price?,"Packaging price depends on product type, dimen..."
18,company,What is PackPro Solutions?,PackPro Solutions is an emerging packaging com...
19,support,Can I speak to the sales team?,Yes. If your question requires a customized qu...

In [8]:
df = pd.DataFrame(knowledge_base)

display(df)

,category,question,answer
0,products,What products do you offer?,"PackPro Solutions offers custom boxes, mailer ..."
1,products,Do you make custom boxes?,Yes. We manufacture customized packaging boxes...
2,products,Do you make mailer boxes?,Yes. We provide custom mailer boxes suitable f...
3,products,Do you make gift boxes?,Yes. We offer customized gift boxes with diffe...
4,materials,What materials do you use?,"We offer kraft paper, corrugated cardboard, pa..."
5,materials,Do you offer kraft packaging?,Yes. Kraft packaging is available for several ...
6,customization,Can I customize the box size?,"Yes. Customers can provide custom length, widt..."
7,customization,Can you print my logo?,Yes. We provide custom logo and artwork printi...
8,customization,What finishing options are available?,Available finishing options may include matte ...
9,moq,What is your MOQ?,Our standard minimum order quantity is 100 uni...
10,moq,What is the minimum order quantity?,Our standard minimum order quantity is 100 uni...
11,samples,Can I get a sample?,Yes. Samples can be requested before placing a...
12,production,How long does production take?,Standard production generally takes 7 to 14 bu...
13,production,How long will my order take?,The standard production time is approximately ...
14,delivery,Do you provide delivery?,Yes. Delivery arrangements can be discussed ba...
15,quotation,How can I get a quotation?,"To request a quotation, provide the product ty..."
16,quotation,What information is needed for a quote?,"We need your product type, length, width, heig..."
17,pricing,What affects packaging price?,"Packaging price depends on product type, dimen..."
18,company,What is PackPro Solutions?,PackPro Solutions is an emerging packaging com...
19,support,Can I speak to the sales team?,Yes. If your question requires a customized qu...

In [9]:
questions = [item["question"] for item in knowledge_base]

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english"
)

question_vectors = vectorizer.fit_transform(questions)

print("AI retrieval system is ready!")

AI retrieval system is ready!

In [10]:
def chatbot_response(user_input, threshold=0.25):

    user_input = user_input.strip()

    if not user_input:
        return "Please enter a question so I can help you."

    user_vector = vectorizer.transform([user_input])

    similarity_scores = cosine_similarity(
        user_vector,
        question_vectors
    )[0]

    best_index = similarity_scores.argmax()
    best_score = similarity_scores[best_index]

    if best_score < threshold:
        return (
            "I'm sorry, I don't have enough information in my knowledge base "
            "to answer that accurately. Please contact our sales team for assistance."
        )

    return knowledge_base[best_index]["answer"]

In [11]:
test_questions = [
    "What is your minimum order?",
    "Can you make custom boxes?",
    "What materials do you use?",
    "How long does production take?",
    "Can I print my logo?"
]

for question in test_questions:
    print("Customer:", question)
    print("Chatbot:", chatbot_response(question))
    print("-" * 60)

Customer: What is your minimum order?
Chatbot: Our standard minimum order quantity is 100 units. Some customized products may have different requirements.
------------------------------------------------------------
Customer: Can you make custom boxes?
Chatbot: Yes. We manufacture customized packaging boxes according to your required size, material, printing and finishing.
------------------------------------------------------------
Customer: What materials do you use?
Chatbot: We offer kraft paper, corrugated cardboard, paperboard and rigid board packaging.
------------------------------------------------------------
Customer: How long does production take?
Chatbot: Standard production generally takes 7 to 14 business days after artwork approval.
------------------------------------------------------------
Customer: Can I print my logo?
Chatbot: Yes. We provide custom logo and artwork printing on suitable packaging products.
------------------------------------------------------------

In [12]:
def chatbot_with_score(user_input, threshold=0.25):

    user_input = user_input.strip()

    if not user_input:
        return "Please enter a question.", 0

    user_vector = vectorizer.transform([user_input])

    similarity_scores = cosine_similarity(
        user_vector,
        question_vectors
    )[0]

    best_index = similarity_scores.argmax()
    best_score = similarity_scores[best_index]

    if best_score < threshold:
        return (
            "I'm sorry, I don't have enough information to answer that accurately.",
            best_score
        )

    return knowledge_base[best_index]["answer"], best_score

In [13]:
answer, score = chatbot_with_score("Do you make kraft boxes?")

print("Answer:", answer)
print("Confidence Score:", round(score, 3))

Answer: Yes. We manufacture customized packaging boxes according to your required size, material, printing and finishing.
Confidence Score: 0.557

In [14]:
def collect_quote():

    print("\n--- Packaging Quote Request ---")

    product = input("Product type: ")
    length = input("Length: ")
    width = input("Width: ")
    height = input("Height: ")
    quantity = input("Quantity: ")
    material = input("Material: ")
    printing = input("Printing requirements: ")
    finishing = input("Finishing: ")
    city = input("Delivery city: ")

    quote = {
        "product": product,
        "dimensions": f"{length} x {width} x {height}",
        "quantity": quantity,
        "material": material,
        "printing": printing,
        "finishing": finishing,
        "delivery_city": city,
        "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    print("\nQuote information collected successfully!")
    print(json.dumps(quote, indent=4))

    return quote

In [15]:
quote_data = collect_quote()

--- Packaging Quote Request ---
Product type: mailer box
Length: 4
Width: 34
Height: 2
Quantity: 3
Material: kraft
Printing requirements: logo printing
Finishing: matte
Delivery city: Islamabad

Quote information collected successfully!
{
    "product": "mailer box",
    "dimensions": "4 x 34 x 2",
    "quantity": "3",
    "material": "kraft",
    "printing": "logo printing",
    "finishing": "matte",
    "delivery_city": "Islamabad",
    "date": "2026-09-25 18:08:20"
}

In [16]:
with open("quote_requests.json", "a", encoding="utf-8") as file:
    json.dump(quote_data, file, indent=4)
    file.write("\n")

print("Quote request saved successfully!")

Quote request saved successfully!

In [17]:
def run_chatbot():

    print("\n" + "=" * 60)
    print("WELCOME TO PACKPRO SOLUTIONS")
    print("AI-Powered Packaging Assistant")
    print("=" * 60)

    print("Ask me about products, materials, MOQ, samples,")
    print("production, delivery and quotations.")
    print("Type 'quote' for a quotation request.")
    print("Type 'exit' to close the chatbot.")

    while True:

        user_input = input("\nYou: ").strip()

        if user_input.lower() == "exit":
            print("Chatbot: Thank you for contacting PackPro Solutions!")
            break

        if user_input.lower() == "quote":
            collect_quote()
            continue

        response, score = chatbot_with_score(user_input)

        print("\nChatbot:", response)

        if score > 0:
            print("(Retrieval confidence:", round(score, 3), ")")

In [18]:
run_chatbot()

============================================================
WELCOME TO PACKPRO SOLUTIONS
AI-Powered Packaging Assistant
============================================================
Ask me about products, materials, MOQ, samples,
production, delivery and quotations.
Type 'quote' for a quotation request.
Type 'exit' to close the chatbot.

You: You: what materials do you have?

Chatbot: We offer kraft paper, corrugated cardboard, paperboard and rigid board packaging.
(Retrieval confidence: 0.707 )

You: what is moq

Chatbot: Our standard minimum order quantity is 100 units, although MOQ can vary depending on the product and customization.
(Retrieval confidence: 1.0 )

You: can you print my logo

Chatbot: Yes. We provide custom logo and artwork printing on suitable packaging products.
(Retrieval confidence: 1.0 )

You: quote

--- Packaging Quote Request ---
Product type: i want to  order
Length: exit
Width: 23
Height: 12
Quantity: 6
Material: kraft
Printing requirements: mate
Finishing: 12
Delivery city: peshawar

Quote information collected successfully!
{
    "product": "i want to  order",
    "dimensions": "exit x 23 x 12",
    "quantity": "6",
    "material": "kraft",
    "printing": "mate",
    "finishing": "12",
    "delivery_city": "peshawar",
    "date": "2026-09-25 18:12:52"
}

You: exit
Chatbot: Thank you for contacting PackPro Solutions!

In [19]:
test_cases = [
    {
        "input": "What is your MOQ?",
        "expected_category": "moq"
    },
    {
        "input": "Do you make custom boxes?",
        "expected_category": "products"
    },
    {
        "input": "What materials are available?",
        "expected_category": "materials"
    },
    {
        "input": "Can I get a sample?",
        "expected_category": "samples"
    },
    {
        "input": "How many days does production take?",
        "expected_category": "production"
    },
    {
        "input": "Can you print my company logo?",
        "expected_category": "customization"
    },
    {
        "input": "Do you deliver?",
        "expected_category": "delivery"
    }
]

print("Testing", len(test_cases), "scenarios...\n")

for test in test_cases:

    answer, score = chatbot_with_score(test["input"])

    print("Input:", test["input"])
    print("Answer:", answer)
    print("Score:", round(score, 3))
    print("-" * 60)

Testing 7 scenarios...

Input: What is your MOQ?
Answer: Our standard minimum order quantity is 100 units, although MOQ can vary depending on the product and customization.
Score: 1.0
------------------------------------------------------------
Input: Do you make custom boxes?
Answer: Yes. We manufacture customized packaging boxes according to your required size, material, printing and finishing.
Score: 1.0
------------------------------------------------------------
Input: What materials are available?
Answer: We offer kraft paper, corrugated cardboard, paperboard and rigid board packaging.
Score: 0.5
------------------------------------------------------------
Input: Can I get a sample?
Answer: Yes. Samples can be requested before placing a bulk production order.
Score: 1.0
------------------------------------------------------------
Input: How many days does production take?
Answer: Standard production generally takes 7 to 14 business days after artwork approval.
Score: 0.849
------------------------------------------------------------
Input: Can you print my company logo?
Answer: Yes. We provide custom logo and artwork printing on suitable packaging products.
Score: 1.0
------------------------------------------------------------
Input: Do you deliver?
Answer: I'm sorry, I don't have enough information to answer that accurately.
Score: 0.0
------------------------------------------------------------

In [20]:
edge_cases = [
    "",
    "hello",
    "What is the weather today?",
    "Can you repair my laptop?",
    "123456789",
    "MOQ?????",
    "CUSTOM BOXES!!!"
]

print("EDGE CASE TESTING")
print("=" * 60)

for question in edge_cases:

    answer, score = chatbot_with_score(question)

    print("Input:", repr(question))
    print("Response:", answer)
    print("Score:", round(score, 3))
    print("-" * 60)

EDGE CASE TESTING
============================================================
Input: ''
Response: Please enter a question.
Score: 0
------------------------------------------------------------
Input: 'hello'
Response: I'm sorry, I don't have enough information to answer that accurately.
Score: 0.0
------------------------------------------------------------
Input: 'What is the weather today?'
Response: I'm sorry, I don't have enough information to answer that accurately.
Score: 0.0
------------------------------------------------------------
Input: 'Can you repair my laptop?'
Response: I'm sorry, I don't have enough information to answer that accurately.
Score: 0.0
------------------------------------------------------------
Input: '123456789'
Response: I'm sorry, I don't have enough information to answer that accurately.
Score: 0.0
------------------------------------------------------------
Input: 'MOQ?????'
Response: Our standard minimum order quantity is 100 units, although MOQ can vary depending on the product and customization.
Score: 1.0
------------------------------------------------------------
Input: 'CUSTOM BOXES!!!'
Response: Yes. We manufacture customized packaging boxes according to your required size, material, printing and finishing.
Score: 0.849
------------------------------------------------------------

In [21]:
conversation_log = []

def log_conversation(user_input, response):

    record = {
        "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": user_input,
        "chatbot": response
    }

    conversation_log.append(record)

    with open("conversation_log.json", "w", encoding="utf-8") as file:
        json.dump(conversation_log, file, indent=4)

In [22]:
question = "What materials do you offer?"

answer = chatbot_response(question)

log_conversation(question, answer)

print("Conversation logged successfully!")
print("User:", question)
print("Bot:", answer)

Conversation logged successfully!
User: What materials do you offer?
Bot: We offer kraft paper, corrugated cardboard, paperboard and rigid board packaging.

In [23]:
print("PROJECT FILES")
print("=" * 40)

for file in os.listdir("."):
    print(file)

PROJECT FILES
========================================
.config
conversation_log.json
packaging_knowledge.json
quote_requests.json
sample_data